-- Realtime attendance: one table. Apply it once to the database in .env, for
-- example:
--
--     psql "host=127.0.0.1 dbname=attendance user=attendance" -f schema.sql
--
-- The id is a UUID v7 generated by the application, so rows sort by creation
-- time and no sequence is shared between processes.
CREATE TABLE IF NOT EXISTS check_ins (
    id uuid PRIMARY KEY,
    student text NOT NULL CHECK (length(student) BETWEEN 1 AND 80),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS check_ins_created_at ON check_ins (created_at DESC);
