package initweb

import (
	"embed"
	"io/fs"
	"strings"

	"ahdcode/internal/ahdversion"
)

//go:embed docbundle
var projectDocs embed.FS

// documentationManifest is the exact English snapshot copied into every
// generated Web project. Turkish files, historical examples, and QA notes
// are intentionally absent.
var documentationManifest = []string{
	"ARCHIVE.md",
	"BITS.md",
	"CLASSES.md",
	"CLI.md",
	"COLLECTIONS.md",
	"CONTROL_FLOW.md",
	"CSV.md",
	"DATA.md",
	"DIAGNOSTICS.md",
	"ENV.md",
	"ERRORS.md",
	"EXCEL.md",
	"FILESYSTEM.md",
	"FORMATTER.md",
	"FUNCTIONS.md",
	"FUNDAMENTALS.md",
	"GETTING_STARTED.md",
	"HTML.md",
	"HTTP.md",
	"IDENTITY.md",
	"INSTALLATION.md",
	"JSON.md",
	"KEYVALUE.md",
	"LANGUAGE_TOUR.md",
	"LATEX.md",
	"LISTS.md",
	"LIST_API.md",
	"LSP.md",
	"MATH.md",
	"MODULES.md",
	"MYSQL.md",
	"NUMERIC.md",
	"PDF.md",
	"PLOT.md",
	"PRACTICAL_MODULES.md",
	"PROTOCOLS.md",
	"REGEX.md",
	"REPL.md",
	"REQUIRE.md",
	"SECURITY.md",
	"SMTP.md",
	"SQLITE.md",
	"STATISTICS.md",
	"STRING_API.md",
	"STUDENT_GUIDE_EN.md",
	"TIME.md",
	"TYPES_AND_NULL.md",
	"WEB.md",
	"WORD.md",
	"XML.md",
	"README.md",
	"AHDCODE_LANGUAGE_SPEC_v0.1.md",
}

func documentationFiles(options Options) []fileSpec {
	files := []fileSpec{
		{relPath: "AHDCODE.md", perm: 0o644, content: []byte(renderAHDCODE(options))},
		{relPath: "Documents/PROJECT.md", perm: 0o644, content: []byte(renderProjectDoc(options))},
	}
	for _, name := range documentationManifest {
		content, err := fs.ReadFile(projectDocs, "docbundle/"+name)
		if err != nil {
			continue
		}
		files = append(files, fileSpec{
			relPath: "Documents/AhdCode/" + name,
			perm:    0o644,
			content: append([]byte("<!-- Exact-version documentation: "+ahdversion.Display+" -->\n\n"), content...),
		})
	}
	return files
}

func renderAHDCODE(options Options) string {
	var b strings.Builder
	b.WriteString("# AHDCODE.md\n\n")
	b.WriteString("This project was generated by **" + ahdversion.Display + "**.\n\n")
	b.WriteString("Starter: **" + options.starterTitle() + "**\n\n")
	b.WriteString("## How to read this tree\n\n")
	b.WriteString("- `:=` binds a name. `=` assigns to a name that already exists.\n")
	b.WriteString("- `bring` imports a standard or framework module.\n")
	b.WriteString("- `require(\"path.ahd\")` includes another source file in this project.\n")
	b.WriteString("- Application configuration is validated in `Config/`. Pages do not call `Env` directly.\n\n")
	b.WriteString("## Documentation\n\n")
	b.WriteString("English reference copies for this AhdCode version live in `Documents/AhdCode/`.\n")
	b.WriteString("Start with `Documents/AhdCode/WEB.md` and `Documents/AhdCode/CLI.md`.\n")
	b.WriteString("`Documents/PROJECT.md` describes this application.\n\n")
	b.WriteString("These files are for humans and assistants. They are not loaded at runtime.\n")
	b.WriteString("Deleting `AHDCODE.md` or `Documents/` does not change `ahdcode run`, `dev`, or `build`.\n")
	b.WriteString("They are not published by the Web server.\n")
	return b.String()
}

func renderProjectDoc(options Options) string {
	var b strings.Builder
	b.WriteString("# " + options.AppName + "\n\n")
	b.WriteString("Generated by " + ahdversion.Display + " as the **" + options.starterTitle() + "** starter.\n\n")
	switch options.Starter {
	case StarterMVC:
		b.WriteString("This application uses an MVC layout: `Routes/`, `Controllers/`, `Models/`, `Views/`, and `Components/`.\n")
		b.WriteString("Public pages list members by name and role. Signed-in members can open only their own profile.\n")
		b.WriteString("Administrators can list, view, create, edit names, and delete members after confirmation. Deletes are POST-only and CSRF-protected.\n")
		b.WriteString("Public identifiers are `public_id` values from `Identity.id()`, never numeric database ids.\n")
	case StarterCRUD:
		b.WriteString("This application uses a flatter CRUD layout: `app.ahd`, `routes.ahd`, `auth.ahd`, `users.ahd`, and `Views/`.\n")
		b.WriteString("Public pages list members by name and role. Signed-in members can open only their own profile.\n")
		b.WriteString("Administrators can list, view, create, edit names, and delete members after confirmation. Deletes are POST-only and CSRF-protected.\n")
		b.WriteString("Public identifiers are `public_id` values from `Identity.id()`, never numeric database ids.\n")
	case StarterAdmin:
		b.WriteString("This application has a public home page and a signed-in administrator dashboard.\n")
	case StarterBasic:
		b.WriteString("This application is a ready shell with environment and mail configuration.\n")
	default:
		b.WriteString("This application is a minimal public Web shell.\n")
	}
	b.WriteString("\nRun it with:\n\n```\nahdcode dev app.ahd\n```\n")
	return b.String()
}
